// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD9WBjtP965QX6kUlkxJFzgZcAMT4XMrk',
    appId: '1:243729352240:web:f323e92b4567344f038ff5',
    messagingSenderId: '243729352240',
    projectId: 'test-app-f1170',
    authDomain: 'test-app-f1170.firebaseapp.com',
    databaseURL: 'https://test-app-f1170-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-f1170.firebasestorage.app',
    measurementId: 'G-MXWVE5522G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBItKPt_R0vfLhkRvWHQoNRHASObWpmWhs',
    appId: '1:243729352240:android:b3763dc4bb859a54038ff5',
    messagingSenderId: '243729352240',
    projectId: 'test-app-f1170',
    databaseURL: 'https://test-app-f1170-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-f1170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaAp2ns0Piu9kFlG1ynGHVfUmposSMVYg',
    appId: '1:243729352240:ios:c518c902ca79e98b038ff5',
    messagingSenderId: '243729352240',
    projectId: 'test-app-f1170',
    databaseURL: 'https://test-app-f1170-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-f1170.firebasestorage.app',
    iosBundleId: 'com.app.driving.drivingMobileApp',
  );

}